# Generated by Django 4.0.2 on 2022-02-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokedexCreature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Type_1', models.CharField(db_column='Type 1', max_length=20)),
                ('Type_2', models.CharField(db_column='Type 2', max_length=20)),
                ('Total', models.IntegerField()),
                ('HP', models.IntegerField()),
                ('Attack', models.IntegerField()),
                ('Defense', models.IntegerField()),
                ('Sp_Atk', models.IntegerField(db_column='Sp. Atk')),
                ('Sp_Def', models.IntegerField(db_column='Sp. Def')),
                ('Speed', models.IntegerField()),
                ('Generation', models.IntegerField()),
                ('Legendary', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('pokedex_creature_id', models.IntegerField(primary_key=True, serialize=False)),
                ('trainer_id', models.IntegerField(null=True)),
                ('surname', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
